"""The CrowPanel 5" + SquareLine + LVGL 8.3.11 setup guide (also in docs/SETUP.md)."""

SETUP_GUIDE = r"""
# SquareLine Studio + LVGL 8.3.11 setup for CrowPanel 5.0" (Arduino IDE)

This MCP generates `.spj` projects that match this exact toolchain. Set
SquareLine and the Arduino side up the same way so exports compile on the board.

## 1. Versions to match
| Piece            | Version                                   |
|------------------|-------------------------------------------|
| Display          | Elecrow CrowPanel 5.0" HMI (ESP32, 800x480) |
| LVGL             | **8.3.11** (from the Elecrow CrowPanel library) |
| SquareLine Studio| **1.4.2** (any 1.4.x works; set LVGL to 8.3) |
| Colour depth     | 16-bit (RGB565)                            |
| Export           | Arduino, "flat export" ON                  |

## 2. SquareLine Studio project settings
When you open a generated `.spj` (or create a new project manually) use:
- **Type / Board:** *Arduino with TFT_eSPI*
- **Resolution:** 800 x 480, **Rotation:** 0, **Shape:** Rectangle
- **LVGL version:** 8.3.11
- **Colour depth:** 16-bit
- **Project export** → *Flat export* enabled
- **File → Project Settings** → set the `UI Files Export Path` to your Arduino
  sketch folder (e.g. `.../CrowPanel_UI/ui`).

> SquareLine's "Arduino with TFT_eSPI" board is only the export template. The
> CrowPanel does **not** use TFT_eSPI — you drive the panel with LovyanGFX on
> the Arduino side (step 4) and just call the generated `ui_init()`.

## 3. Opening an MCP-generated project
The MCP writes `<Name>.spj`. In SquareLine: **File → Open Project…** and pick the
`.spj`. (Or drop the folder into `Documents/SquareLine/Projects/`.) Tweak
visually if you like, then **Export → Export UI Files**.

## 4. Arduino IDE libraries (CrowPanel side)
Install these — versions matter:
- **LVGL 8.3.11** — copy the `lvgl` folder from the Elecrow library
  (`CrowPanel-5.0-HMI-ESP32-Display-800x480/.../libraries/lvgl`) into your
  Arduino `libraries/`, **or** install "lvgl" 8.3.11 via Library Manager.
- **LovyanGFX** — from the same Elecrow `libraries/` folder.
- **gt911** touch driver and **PCA9557** I/O expander — from the Elecrow
  `libraries/` folder.
- **`lv_conf.h`** — use the one from the Elecrow library (place it next to the
  `lvgl` folder, i.e. directly in `libraries/`). Confirm it has
  `#define LV_COLOR_DEPTH 16` and `#define LV_TICK_CUSTOM 1`.

Board settings: **ESP32 Dev Module** (or your CrowPanel board), PSRAM enabled,
Flash 8MB/16MB per your unit.

## 5. Wiring the exported UI into your sketch
Put the exported `ui/` folder next to your `.ino`, then:

```cpp
#include <lvgl.h>
#include <LovyanGFX.hpp>   // CrowPanel display + GT911 touch driver
#include "ui/ui.h"         // generated by SquareLine

void setup() {
  lv_init();
  // ... CrowPanel display + touch init (from the Elecrow example sketch) ...
  ui_init();               // <-- builds the screens you designed
}

void loop() {
  lv_timer_handler();
  delay(5);
}
```

Reference the Elecrow CrowPanel example sketch for the exact LovyanGFX display
config and the `my_disp_flush` / `my_touchpad_read` callbacks — keep those, and
just add `#include "ui/ui.h"` and `ui_init()`.

## 6. Naming widgets
SquareLine turns each widget **Name** into a C identifier (`ui_<Name>`). Use
unique, code-safe names (letters/digits/underscore) — the MCP does not rename
for you, so avoid spaces and duplicates.
""".strip()
