"""
Serialization of the in-memory UI model into a SquareLine Studio ``.spj``
project file.

The ``.spj`` format is undocumented JSON.  This module was written by
reverse-engineering a real project generated by SquareLine Studio 1.4.2 for
LVGL 8.3.11 (an Elecrow CrowPanel export).  The structure is:

    {
      "root":     <STARTEVENTS node whose children are the SCREEN nodes>,
      "animations": [],
      "selected_theme": "",
      "info":     <project settings block>
    }

Every object in the tree (screen or widget) looks like::

    {
      "guid": "GUID<n>-<n>S<n>",
      "deepid": <random int>,
      "children": [ ...child widgets... ],   # containers only
      "locked": false,
      "properties": [ <property records...> ],
      "saved_objtypeKey": "SCREEN" | "PANEL" | "LABEL" | ...
    }

A *property record* is a flat dict identified by ``strtype`` (e.g.
``"OBJECT/Name"``) and carrying its value in one of several keys depending on
``InheritedType``:

    InheritedType  meaning        value key
    -------------  -------------  -----------------------------
    1              header/group   (none)
    2              boolean        strval "True"/"False"
    3              enum           strval "CENTER"
    4              event          childs
    5              image/asset    strval "assets/foo.png"
    6              integer        integer
    7              int array      intarray [x, y] / [r,g,b,a]
    9              guid reference  strval "<guid>"
    10             string         strval "text"
    11             style          part + childs
    13             layout         extra layout keys

``nid`` is a per-record identifier; SquareLine uses stable hashes but any
unique 32-bit integer works and is regenerated on the next save.
"""

from __future__ import annotations

import random
from typing import Any, Dict, List, Optional

# --- InheritedType constants -------------------------------------------------

IT_HEADER = 1
IT_BOOL = 2
IT_ENUM = 3
IT_EVENT = 4
IT_IMAGE = 5
IT_INT = 6
IT_INTARRAY = 7
IT_GUIDREF = 9
IT_STRING = 10
IT_STYLE = 11
IT_LAYOUT = 13

# Flags observed on specific records in genuine projects.  They are opaque bit
# masks that SquareLine writes; we reproduce the ones that appear on every
# object so the file matches what the editor expects.
FLAG_TRANSFORM = 17       # OBJECT/Position and OBJECT/Size
FLAG_GROUP = 1048576      # OBJECT/Flags and OBJECT/States group headers


def new_nid() -> int:
    """A fresh signed 32-bit property id."""
    return random.randint(-(2 ** 31), 2 ** 31 - 1)


def new_guid() -> str:
    """A globally-unique object id in SquareLine's ``GUID<n>-<n>S<n>`` shape."""
    return "GUID{}-{}S{}".format(
        random.randint(10_000_000, 99_999_999),
        random.randint(100_000, 999_999),
        random.randint(1_000_000, 99_999_999),
    )


def new_deepid() -> int:
    return random.randint(-(2 ** 31), 2 ** 31 - 1)


# --- property record builders ------------------------------------------------


def p_header(strtype: str, flags: Optional[int] = None) -> Dict[str, Any]:
    rec: Dict[str, Any] = {"nid": new_nid(), "strtype": strtype, "InheritedType": IT_HEADER}
    if flags is not None:
        rec["flags"] = flags
    return rec


def p_bool(strtype: str, value: bool) -> Dict[str, Any]:
    return {
        "nid": new_nid(),
        "strtype": strtype,
        "strval": "True" if value else "False",
        "InheritedType": IT_BOOL,
    }


def p_enum(strtype: str, value: str) -> Dict[str, Any]:
    return {"nid": new_nid(), "strtype": strtype, "strval": value, "InheritedType": IT_ENUM}


def p_string(strtype: str, value: str) -> Dict[str, Any]:
    return {"nid": new_nid(), "strtype": strtype, "strval": value, "InheritedType": IT_STRING}


def p_int(strtype: str, value: Optional[int]) -> Dict[str, Any]:
    rec: Dict[str, Any] = {"nid": new_nid(), "strtype": strtype, "InheritedType": IT_INT}
    if value is not None:
        rec["integer"] = value
    return rec


def p_intarray(strtype: str, values: List[int], flags: Optional[int] = None) -> Dict[str, Any]:
    rec: Dict[str, Any] = {
        "nid": new_nid(),
        "strtype": strtype,
        "intarray": list(values),
        "InheritedType": IT_INTARRAY,
    }
    if flags is not None:
        rec["flags"] = flags
    return rec


def p_image(strtype: str, path: str) -> Dict[str, Any]:
    return {"nid": new_nid(), "strtype": strtype, "strval": path, "InheritedType": IT_IMAGE}


def p_guidref(strtype: str, guid: str) -> Dict[str, Any]:
    return {"nid": new_nid(), "strtype": strtype, "strval": guid, "InheritedType": IT_GUIDREF}


def p_style(strtype: str, part: str, summary: str, style_children: List[Dict[str, Any]]) -> Dict[str, Any]:
    """A style property.  ``part`` is e.g. ``lv.PART.MAIN``.  ``style_children``
    are the ``_style/*`` records that live under the DEFAULT state."""
    return {
        "part": part,
        "childs": [
            {
                "nid": new_nid(),
                "strtype": "_style/StyleState",
                "strval": "DEFAULT",
                "childs": style_children,
                "InheritedType": IT_HEADER,
            }
        ],
        "nid": new_nid(),
        "strtype": strtype,
        "strval": summary,
        "InheritedType": IT_STYLE,
    }


# --- style child builders (the "_style/*" records) ---------------------------
# Exposed to the model so a widget can carry a small set of common style tweaks.

STYLE_BUILDERS = {
    "bg_color": lambda v: p_intarray("_style/Bg_Color", v),
    "bg_opa": lambda v: p_int("_style/Bg_Opa", v),
    "bg_image": lambda v: p_image("_style/Bg_Image", v),
    "radius": lambda v: p_int("_style/Bg_Radius", v),
    "border_color": lambda v: p_intarray("_style/Border_Color", v),
    "border_width": lambda v: p_int("_style/Border width", v),
    "text_color": lambda v: p_intarray("_style/Text_Color", v),
    "text_align": lambda v: p_enum("_style/Text_Align", v),
    "text_font": lambda v: p_enum("_style/Text_Font", v),
    "pad": lambda v: p_intarray("_style/Padding", v),
}


def build_style_children(styles: Dict[str, Any]) -> List[Dict[str, Any]]:
    children: List[Dict[str, Any]] = []
    for key, value in styles.items():
        builder = STYLE_BUILDERS.get(key)
        if builder is not None:
            children.append(builder(value))
    return children


# --- shared OBJECT property block --------------------------------------------
# Every widget carries the same OBJECT/* base (name, geometry, flags, states).
# Screens are top-level and omit the geometry/child-only flags.


def object_base_props(
    *,
    name: str,
    is_screen: bool,
    x: int = 0,
    y: int = 0,
    w: int = 100,
    h: int = 50,
    align: str = "TOP_LEFT",
    hidden: bool = False,
    clickable: bool = True,
    checkable: bool = False,
    disabled: bool = False,
) -> List[Dict[str, Any]]:
    props: List[Dict[str, Any]] = [
        p_string("OBJECT/Name", name),
        p_header("OBJECT/Layout"),
        {
            "Flow": 0,
            "Wrap": False,
            "Reversed": False,
            "MainAlignment": 0,
            "CrossAlignment": 0,
            "TrackAlignment": 0,
            "LayoutType": 0,
            "nid": new_nid(),
            "strtype": "OBJECT/Layout_type",
            "strval": "No_layout",
            "InheritedType": IT_LAYOUT,
        },
        p_header("OBJECT/Transform"),
    ]

    if not is_screen:
        props += [
            p_intarray("OBJECT/Position", [x, y], flags=FLAG_TRANSFORM),
            p_intarray("OBJECT/Size", [w, h], flags=FLAG_TRANSFORM),
            p_enum("OBJECT/Align", align),
        ]

    props.append(p_header("OBJECT/Flags", flags=FLAG_GROUP))
    props.append(p_bool("OBJECT/Hidden", hidden))
    props.append(p_bool("OBJECT/Clickable", clickable))
    props.append(p_bool("OBJECT/Checkable", checkable))
    props.append(p_bool("OBJECT/Press_lock", True))
    if not is_screen:
        props.append(p_bool("OBJECT/Click_focusable", True))
    props.append(p_bool("OBJECT/Adv_hittest", False))
    props.append(p_bool("OBJECT/Ignore_layout", False))
    if not is_screen:
        props.append(p_bool("OBJECT/Floating", False))
    props.append(p_bool("OBJECT/Overflow_visible", False))
    props.append(p_bool("OBJECT/Flex_in_new_track", False))
    if not is_screen:
        props += [
            p_bool("OBJECT/Event_bubble", False),
            p_bool("OBJECT/Gesture_bubble", True),
            p_bool("OBJECT/Snappable", True),
        ]
    props.append(p_bool("OBJECT/Scrollable", not is_screen))
    props.append(p_bool("OBJECT/Scroll_elastic", True))
    props.append(p_bool("OBJECT/Scroll_momentum", True))
    if not is_screen:
        props.append(p_bool("OBJECT/Scroll_on_focus", False))
        props.append(p_bool("OBJECT/Scroll_chain", True))
    props += [
        p_bool("OBJECT/Scroll_with_arrow", False),
        p_bool("OBJECT/Scroll_one", False),
        p_enum("OBJECT/Scrollbar_mode", "AUTO"),
        p_enum("OBJECT/Scroll_direction", "ALL"),
        p_header("OBJECT/States", flags=FLAG_GROUP),
        p_bool("OBJECT/Checked", False),
    ]
    if not is_screen:
        props.append(p_bool("OBJECT/Disabled", disabled))
    props += [
        p_bool("OBJECT/Focused", False),
        p_bool("OBJECT/Pressed", False),
        p_bool("OBJECT/Edited", False),
        p_bool("OBJECT/User_1", False),
        p_bool("OBJECT/User_2", False),
        p_bool("OBJECT/User_3", False),
        p_bool("OBJECT/User_4", False),
    ]
    return props


# --- event builder -----------------------------------------------------------


def change_screen_event(trigger: str, target_guid: str, target_name: str,
                        fade_mode: str = "MOVE_LEFT", speed: int = 500, delay: int = 0) -> Dict[str, Any]:
    """A ``_event/EventHandler`` record that switches to another screen."""
    return {
        "disabled": False,
        "nid": new_nid(),
        "strtype": "_event/EventHandler",
        "strval": trigger,
        "childs": [
            p_string("_event/name", "Event1"),
            p_string("_event/condition_C", ""),
            p_string("_event/condition_P", ""),
            {
                "nid": new_nid(),
                "strtype": "_event/action",
                "strval": "CHANGE SCREEN",
                "childs": [
                    p_string("CHANGE SCREEN/Name", "CHANGE SCREEN"),
                    p_string(
                        "CHANGE SCREEN/Call",
                        "ChangeScreen( <{Screen_to}>, lv.SCR_LOAD_ANIM.<{Fade_mode}>, <{Speed}>, <{Delay}>)",
                    ),
                    p_string(
                        "CHANGE SCREEN/CallC",
                        "_ui_screen_change( &<{Screen_to}>, LV_SCR_LOAD_ANIM_<{Fade_mode}>, "
                        "<{Speed}>, <{Delay}>, &<{Screen_to}>_screen_init);",
                    ),
                    p_guidref("CHANGE SCREEN/Screen_to", target_guid),
                    p_enum("CHANGE SCREEN/Fade_mode", fade_mode),
                    p_int("CHANGE SCREEN/Speed", speed),
                    p_int("CHANGE SCREEN/Delay", delay),
                ],
                "InheritedType": IT_STRING,
            },
        ],
        "InheritedType": IT_EVENT,
    }
