"""
Serialization of the in-memory UI model into a SquareLine Studio ``.spj``
project file.

The ``.spj`` format is undocumented JSON.  This module was written by
reverse-engineering a real project generated by SquareLine Studio 1.4.2 for
LVGL 8.3.11 (an Elecrow CrowPanel export).  The structure is:

    {
      "root":     <STARTEVENTS node whose children are the SCREEN nodes>,
      "animations": [],
      "selected_theme": "",
      "info":     <project settings block>
    }

Every object in the tree (screen or widget) looks like::

    {
      "guid": "GUID<n>-<n>S<n>",
      "deepid": <random int>,
      "children": [ ...child widgets... ],   # containers only
      "locked": false,
      "properties": [ <property records...> ],
      "saved_objtypeKey": "SCREEN" | "PANEL" | "LABEL" | ...
    }

A *property record* is a flat dict identified by ``strtype`` (e.g.
``"OBJECT/Name"``) and carrying its value in one of several keys depending on
``InheritedType``:

    InheritedType  meaning        value key
    -------------  -------------  -----------------------------
    1              header/group   (none)
    2              boolean        strval "True"/"False"
    3              enum           strval "CENTER"
    4              event          childs
    5              image/asset    strval "assets/foo.png"
    6              integer        integer
    7              int array      intarray [x, y] / [r,g,b,a]
    9              guid reference  strval "<guid>"
    10             string         strval "text"
    11             style          part + childs
    13             layout         extra layout keys

``nid`` is a per-record identifier; SquareLine uses stable hashes but any
unique 32-bit integer works and is regenerated on the next save.
"""

from __future__ import annotations

import random
from typing import Any, Dict, List, Optional

# --- InheritedType constants -------------------------------------------------

IT_HEADER = 1
IT_BOOL = 2
IT_ENUM = 3
IT_EVENT = 4
IT_IMAGE = 5
IT_INT = 6
IT_INTARRAY = 7
IT_GUIDREF = 9
IT_STRING = 10
IT_STYLE = 11
IT_LAYOUT = 13

# Flags observed on specific records in genuine projects.  They are opaque bit
# masks that SquareLine writes; we reproduce the ones that appear on every
# object so the file matches what the editor expects.
FLAG_TRANSFORM = 17       # OBJECT/Position and OBJECT/Size
FLAG_GROUP = 1048576      # OBJECT/Flags and OBJECT/States group headers


def new_nid() -> int:
    """A fresh signed 32-bit property id."""
    return random.randint(-(2 ** 31), 2 ** 31 - 1)


def new_guid() -> str:
    """A globally-unique object id in SquareLine's ``GUID<n>-<n>S<n>`` shape."""
    return "GUID{}-{}S{}".format(
        random.randint(10_000_000, 99_999_999),
        random.randint(100_000, 999_999),
        random.randint(1_000_000, 99_999_999),
    )


def new_deepid() -> int:
    return random.randint(-(2 ** 31), 2 ** 31 - 1)


# --- property record builders ------------------------------------------------


def p_header(strtype: str, flags: Optional[int] = None) -> Dict[str, Any]:
    rec: Dict[str, Any] = {"nid": new_nid(), "strtype": strtype, "InheritedType": IT_HEADER}
    if flags is not None:
        rec["flags"] = flags
    return rec


def p_bool(strtype: str, value: bool) -> Dict[str, Any]:
    return {
        "nid": new_nid(),
        "strtype": strtype,
        "strval": "True" if value else "False",
        "InheritedType": IT_BOOL,
    }


def p_enum(strtype: str, value: str) -> Dict[str, Any]:
    return {"nid": new_nid(), "strtype": strtype, "strval": value, "InheritedType": IT_ENUM}


def p_string(strtype: str, value: str) -> Dict[str, Any]:
    return {"nid": new_nid(), "strtype": strtype, "strval": value, "InheritedType": IT_STRING}


def p_int(strtype: str, value: Optional[int]) -> Dict[str, Any]:
    rec: Dict[str, Any] = {"nid": new_nid(), "strtype": strtype, "InheritedType": IT_INT}
    if value is not None:
        rec["integer"] = value
    return rec


def p_intarray(strtype: str, values: List[int], flags: Optional[int] = None) -> Dict[str, Any]:
    rec: Dict[str, Any] = {
        "nid": new_nid(),
        "strtype": strtype,
        "intarray": list(values),
        "InheritedType": IT_INTARRAY,
    }
    if flags is not None:
        rec["flags"] = flags
    return rec


def p_image(strtype: str, path: str) -> Dict[str, Any]:
    return {"nid": new_nid(), "strtype": strtype, "strval": path, "InheritedType": IT_IMAGE}


def p_guidref(strtype: str, guid: str) -> Dict[str, Any]:
    return {"nid": new_nid(), "strtype": strtype, "strval": guid, "InheritedType": IT_GUIDREF}


_IT_VALUE_KEY = {
    IT_BOOL: "strval",
    IT_ENUM: "strval",
    IT_IMAGE: "strval",
    IT_GUIDREF: "strval",
    IT_STRING: "strval",
    IT_INT: "integer",
    IT_INTARRAY: "intarray",
}


def p_value(strtype: str, it: int, value: Any) -> Dict[str, Any]:
    """Generic property record for a given InheritedType.

    Booleans are coerced to SquareLine's "True"/"False" strings. ``None`` leaves
    the value key out (SquareLine treats that as unset, e.g. an empty delay).
    """
    rec: Dict[str, Any] = {"nid": new_nid(), "strtype": strtype, "InheritedType": it}
    if it == IT_HEADER:
        return rec
    key = _IT_VALUE_KEY.get(it, "strval")
    if it == IT_BOOL:
        rec[key] = "True" if (value if isinstance(value, bool) else str(value).lower() in
                              ("1", "true", "yes", "on")) else "False"
    elif value is not None:
        rec[key] = value
    return rec


def _style_state(state: str, style_children: List[Dict[str, Any]]) -> Dict[str, Any]:
    return {
        "nid": new_nid(),
        "strtype": "_style/StyleState",
        "strval": state,
        "childs": style_children,
        "InheritedType": IT_HEADER,
    }


def p_style(strtype: str, part: str, summary: str,
            states: Any = None) -> Dict[str, Any]:
    """A style property record for one part of a widget.

    ``part`` is e.g. ``lv.PART.MAIN``. ``states`` may be:
      * a list  -> those records under the DEFAULT state, or
      * a dict {state_name: [records]} -> one StyleState child per state.
    A DEFAULT state is always emitted (SquareLine expects it first)."""
    if states is None:
        states = {}
    if isinstance(states, list):
        states = {"DEFAULT": states}
    childs = [_style_state("DEFAULT", states.get("DEFAULT", []))]
    for name, recs in states.items():
        if name != "DEFAULT":
            childs.append(_style_state(name, recs))
    return {
        "part": part,
        "childs": childs,
        "nid": new_nid(),
        "strtype": strtype,
        "strval": summary,
        "InheritedType": IT_STYLE,
    }


# --- shared OBJECT property block --------------------------------------------
# Every widget carries the same OBJECT/* base (name, geometry, flags, states).
# Screens are top-level and omit the geometry/child-only flags.


# Layout kinds for OBJECT/Layout_type.  Values follow SquareLine's encoding.
_LAYOUTS = {
    "none": {"strval": "No_layout", "LayoutType": 0},
    "flex": {"strval": "Flex_layout", "LayoutType": 1},
    "grid": {"strval": "Grid_layout", "LayoutType": 2},
}
# Flex "Flow" enum -> int (ROW=0, COLUMN=1, ROW_WRAP=2, COLUMN_WRAP=3, ...)
_FLEX_FLOW = {"ROW": 0, "COLUMN": 1, "ROW_WRAP": 2, "COLUMN_WRAP": 3,
              "ROW_REVERSE": 4, "COLUMN_REVERSE": 5}
# Flex alignment enum -> int (START=0, END=1, CENTER=2, SPACE_EVENLY=3,
# SPACE_AROUND=4, SPACE_BETWEEN=5)
_FLEX_ALIGN = {"START": 0, "END": 1, "CENTER": 2, "SPACE_EVENLY": 3,
               "SPACE_AROUND": 4, "SPACE_BETWEEN": 5}


def _layout_record(layout: Optional[Dict[str, Any]]) -> Dict[str, Any]:
    kind = (layout or {}).get("type", "none").lower()
    base = dict(_LAYOUTS.get(kind, _LAYOUTS["none"]))
    rec = {
        "Flow": _FLEX_FLOW.get(str((layout or {}).get("flow", "ROW")).upper(), 0),
        "Wrap": bool((layout or {}).get("wrap", False)),
        "Reversed": False,
        "MainAlignment": _FLEX_ALIGN.get(str((layout or {}).get("main_align", "START")).upper(), 0),
        "CrossAlignment": _FLEX_ALIGN.get(str((layout or {}).get("cross_align", "START")).upper(), 0),
        "TrackAlignment": _FLEX_ALIGN.get(str((layout or {}).get("track_align", "START")).upper(), 0),
        "LayoutType": base["LayoutType"],
        "nid": new_nid(),
        "strtype": "OBJECT/Layout_type",
        "strval": base["strval"],
        "InheritedType": IT_LAYOUT,
    }
    return rec


def object_base_props(
    *,
    name: str,
    is_screen: bool,
    x: int = 0,
    y: int = 0,
    w: int = 100,
    h: int = 50,
    align: str = "TOP_LEFT",
    hidden: bool = False,
    clickable: bool = True,
    checkable: bool = False,
    disabled: bool = False,
    layout: Optional[Dict[str, Any]] = None,
    flags: Optional[Dict[str, Any]] = None,
) -> List[Dict[str, Any]]:
    props: List[Dict[str, Any]] = [
        p_string("OBJECT/Name", name),
        p_header("OBJECT/Layout"),
        _layout_record(layout),
        p_header("OBJECT/Transform"),
    ]

    if not is_screen:
        props += [
            p_intarray("OBJECT/Position", [x, y], flags=FLAG_TRANSFORM),
            p_intarray("OBJECT/Size", [w, h], flags=FLAG_TRANSFORM),
            p_enum("OBJECT/Align", align),
        ]

    props.append(p_header("OBJECT/Flags", flags=FLAG_GROUP))
    props.append(p_bool("OBJECT/Hidden", hidden))
    props.append(p_bool("OBJECT/Clickable", clickable))
    props.append(p_bool("OBJECT/Checkable", checkable))
    props.append(p_bool("OBJECT/Press_lock", True))
    if not is_screen:
        props.append(p_bool("OBJECT/Click_focusable", True))
    props.append(p_bool("OBJECT/Adv_hittest", False))
    props.append(p_bool("OBJECT/Ignore_layout", False))
    if not is_screen:
        props.append(p_bool("OBJECT/Floating", False))
    props.append(p_bool("OBJECT/Overflow_visible", False))
    props.append(p_bool("OBJECT/Flex_in_new_track", False))
    if not is_screen:
        props += [
            p_bool("OBJECT/Event_bubble", False),
            p_bool("OBJECT/Gesture_bubble", True),
            p_bool("OBJECT/Snappable", True),
        ]
    props.append(p_bool("OBJECT/Scrollable", not is_screen))
    props.append(p_bool("OBJECT/Scroll_elastic", True))
    props.append(p_bool("OBJECT/Scroll_momentum", True))
    if not is_screen:
        props.append(p_bool("OBJECT/Scroll_on_focus", False))
        props.append(p_bool("OBJECT/Scroll_chain", True))
    props += [
        p_bool("OBJECT/Scroll_with_arrow", False),
        p_bool("OBJECT/Scroll_one", False),
        p_enum("OBJECT/Scrollbar_mode", "AUTO"),
        p_enum("OBJECT/Scroll_direction", "ALL"),
        p_header("OBJECT/States", flags=FLAG_GROUP),
        p_bool("OBJECT/Checked", False),
    ]
    if not is_screen:
        props.append(p_bool("OBJECT/Disabled", disabled))
    props += [
        p_bool("OBJECT/Focused", False),
        p_bool("OBJECT/Pressed", False),
        p_bool("OBJECT/Edited", False),
        p_bool("OBJECT/User_1", False),
        p_bool("OBJECT/User_2", False),
        p_bool("OBJECT/User_3", False),
        p_bool("OBJECT/User_4", False),
    ]

    # Generic OBJECT/* overrides by suffix (e.g. {"Scrollable": False}).
    if flags:
        want = {"OBJECT/%s" % k: v for k, v in flags.items()}
        for rec in props:
            st = rec.get("strtype")
            if st in want and rec.get("InheritedType") in (IT_BOOL, IT_ENUM):
                v = want[st]
                rec["strval"] = ("True" if v else "False") if isinstance(v, bool) else str(v)
    return props


# Event/action records are built in events.py from the bundled action templates.
